// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAunHgbdxv1tZ4kNmjGLJkG1Jy-EqDlKn4',
    appId: '1:468767635530:web:f337aa9e7af05ae7de4eb3',
    messagingSenderId: '468767635530',
    projectId: 'miam-planning-app',
    authDomain: 'miam-planning-app.firebaseapp.com',
    storageBucket: 'miam-planning-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvDVPBEMjz5p5-z37qhoU1aw6ofjPZuVs',
    appId: '1:468767635530:android:f4ef1129ed615da1de4eb3',
    messagingSenderId: '468767635530',
    projectId: 'miam-planning-app',
    storageBucket: 'miam-planning-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAunHgbdxv1tZ4kNmjGLJkG1Jy-EqDlKn4',
    appId: '1:468767635530:web:86befe7526670dfade4eb3',
    messagingSenderId: '468767635530',
    projectId: 'miam-planning-app',
    authDomain: 'miam-planning-app.firebaseapp.com',
    storageBucket: 'miam-planning-app.firebasestorage.app',
  );
}
